view: m_session_recommendation_product_summary {
  derived_table: {
    sql: select
      ca.account_id
    , currency
    , DATE_TRUNC('HOUR', start_time) AS start_time
    , action_id
    , product_id
    , SUM(impressions) AS impressions
    , SUM(clickthroughs) AS clickthroughs
    , SUM(has_recommendation_purchase) AS has_recommendation_purchase_count
    , SUM(recommendation_purchase_quantity) AS recommendation_converted
    , SUM(recommendation_purchase_revenue) AS recommendation_demand
    , SUM(total_purchases) AS purchases
    , SUM(total_quantity) AS quantity
    , SUM(total_revenue) AS revenue

    from "PUBLIC"."M_SESSION_RECOMMENDATION_PRODUCT_SUMMARY"  srps
    inner join "PUBLIC"."CONFIG_ACCOUNT" ca
    on (srps.account_id=ca.account_id)
    group by ca.account_id,currency ,DATE_TRUNC('HOUR', start_time), action_id, product_id

    ;;
    #datagroup_trigger: personalization_data_summary_default_datagroup
      sql_trigger_value: select current_date() ;;
      cluster_keys:["account_id","action_id","product_id"]

    }


    dimension: currency {
      type: string
      sql: ${TABLE}."CURRENCY" ;;
    }

    dimension: currency_symbol{
      hidden: yes
      sql:
          CASE
          WHEN ${currency} = 'USD' THEN '$'
          WHEN ${currency} = 'EUR' THEN '€'
          WHEN ${currency} = 'AED' THEN 'د.إ'
          WHEN ${currency} = 'ARS' THEN '$'
          WHEN ${currency} = 'AUD' THEN 'A$'
          WHEN ${currency} = 'BGN' THEN 'Лв.'
          WHEN ${currency} = 'BHD' THEN 'BD'
          WHEN ${currency} = 'BRL' THEN 'R$'
          WHEN ${currency} = 'CAD' THEN 'CA$'
          WHEN ${currency} = 'CHF' THEN 'CHf'
          WHEN ${currency} = 'CLP' THEN '$'
          WHEN ${currency} = 'CNY' THEN '¥'
          WHEN ${currency} = 'COP' THEN 'COL$'
          WHEN ${currency} = 'CZK' THEN 'Kč'
          WHEN ${currency} = 'DKK' THEN 'Kr.'
          WHEN ${currency} = 'GBP' THEN '£'
          WHEN ${currency} = 'HKD' THEN 'HK$'
          WHEN ${currency} = 'HRK' THEN 'kn'
          WHEN ${currency} = 'IDR' THEN 'Rp'
          WHEN ${currency} = 'ILS' THEN '₪'
          WHEN ${currency} = 'INR' THEN '₹'
          WHEN ${currency} = 'ISK' THEN 'Íkr'
          WHEN ${currency} = 'JOD' THEN 'د.ا'
          WHEN ${currency} = 'JPY' THEN '¥'
          WHEN ${currency} = 'KRW' THEN '₩'
          WHEN ${currency} = 'KWD' THEN 'KD'
          WHEN ${currency} = 'KZT' THEN '₸'
          WHEN ${currency} = 'MXN' THEN 'Mex$'
          WHEN ${currency} = 'MYR' THEN 'RM'
          WHEN ${currency} = 'NOK' THEN 'kr'
          WHEN ${currency} = 'NZD' THEN 'NZ$'
          WHEN ${currency} = 'OMR' THEN 'ر.ع.'
          WHEN ${currency} = 'PEN' THEN 'S/'
          WHEN ${currency} = 'PHP' THEN '₱'
          WHEN ${currency} = 'PLN' THEN 'zł'
          WHEN ${currency} = 'QAR' THEN 'QR'
          WHEN ${currency} = 'RON' THEN 'lei'
          WHEN ${currency} = 'RUB' THEN '₽'
          WHEN ${currency} = 'SAR' THEN 'SR'
          WHEN ${currency} = 'SEK' THEN 'kr'
          WHEN ${currency} = 'SGD' THEN 'S$'
          WHEN ${currency} = 'THB' THEN '฿'
          WHEN ${currency} = 'TWD' THEN 'NT$'
          WHEN ${currency} = 'UAH' THEN '₴'
          WHEN ${currency} = 'ZAR' THEN 'R'

          ELSE CONCAT(${currency}, ' ')
          END;;
    }

    dimension: account_id {
      label: "Account ID"
      description: "Unique id for site"
      type: number
      value_format_name: id
      sql: ${TABLE}."ACCOUNT_ID" ;;
    }

    dimension: action_id {
      label: "Action ID"
      description: "ID from where recommendation was presented"
      type: number
      value_format_name: id
      sql: ${TABLE}."ACTION_ID" ;;
    }

    measure: clickthroughs {
      label: "Clickthroughs"
      description: "Recommendations clicked"
      type: sum
      sql: ${TABLE}."CLICKTHROUGHS" ;;
    }

    measure: impressions {
      label: "Impressions"
      description: "Recommendation presented"
      type: sum
      sql: ${TABLE}."IMPRESSIONS" ;;
    }

    dimension: price  {
      type: number
      hidden: yes
      sql: ${TABLE}."REVENUE" ;;
    }

    measure: price_sum {
      label: "Total Revenue"
      description: "Total revenue generated by items"
      type: sum
      value_format: "#,##0.00" #"0.00"
      #decimals: 2
      html:
          {{currency_symbol._value }}{{ rendered_value }};;
      sql:  ${price} ;;
    }

    dimension: product_id {
      label: "Product ID"
      type: string
      sql: ${TABLE}."PRODUCT_ID" ;;
    }

    measure: quantity {
      label: "All Units Sold"
      description: "Total quantity sold"
      type: sum

      sql: ${TABLE}."QUANTITY" ;;
    }

    measure: recommendation_converted {
      label: "Recommendation Converted"
      description: "Count of items that were clicked and purchased"
      type: sum
      sql: ${TABLE}."RECOMMENDATION_CONVERTED" ;;
    }

    dimension: recommendation_demand {
      type: number
      hidden: yes
      sql: ${TABLE}."RECOMMENDATION_DEMAND";;
    }

    measure: recommendation_demand_sum {
      label: "Recommendation Revenue"
      description: "Revenue from items that were clicked and purchased"
      type: sum
      value_format: "#,##0.00" #"0.00"
      html:
          {{currency_symbol._value }}{{ rendered_value }};;
      sql: ${recommendation_demand} ;;

    }

    dimension_group: start_time {
      label: "Session"
      description: "Date of the session"
      type: time
      timeframes: [
        hour,
        date,
        week,
        month,
        quarter,
        year

      ]
      convert_tz: yes
      #datatype: date
      sql: ${TABLE}."START_TIME" ;;
    }

    measure: count {
      type: count
      drill_fields: []
    }
  }
